# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.


# Setup
title:               
tagline:             
description:         Ibland kort, ibland l√•ngt. Delvis trams. 
url:                 http://antonmodin.se
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Anton Modin
  url:               https://twitter.com/antonmodin
  email:             anton.modin@gmail.com


